### ISSUE TITLE
how to add the data of ' stackepi'

### ISSUE THREAD

**Issue by karmen-cc** [GenEpi-GenPhySE/epistack#27]
As a novice, I just started to contact R language and epigroup modification. I am not very clear about how to import the expression amount and the corresponding histone modification data. Seeing that you are directly packaging and generating a result file, can you share the intermediate process and the corresponding sample data? Looking forward to your reply.

**Comment by gdevailly** [comment]
The dataset import and formatting is briefly explained in the epistack vignette in both example sections. See:
[https://bioconductor.org/packages/release/bioc/vignettes/epistack/inst/doc/using_epistack.html#example-1-chip-seq-coverage-at-peaks](https://bioconductor.org/packages/release/bioc/vignettes/epistack/inst/doc/using_epistack.html#example-1-chip-seq-coverage-at-peaks)

You need to import Histone mod data and your anchors using `rtracklayer::import()` (or equivalent methods). Expression data are usually a table and can be imported with your favorite table parser. Expression data can be used as an anchor score. Adding the expression as a metadata in the anchor GRange is simple enough once you have decided on a strategy to perform the score <-> anchor association.
